/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets/{asset_id}/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset File */
        get: operations["get_asset_file_api_v1_assets__asset_id___kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write Label */
        post: operations["write_label_api_v1_curation_labels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next Candidate */
        get: operations["next_candidate_api_v1_curation_next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress */
        get: operations["progress_api_v1_curation_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Snapshot */
        post: operations["export_snapshot_api_v1_curation_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Event
         * @description Record an interaction. The timestamp is generated server-side.
         */
        post: operations["record_event_api_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_api_v1_preferences_get"];
        /** Update Preferences */
        put: operations["update_preferences_api_v1_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_search_api_v1_search_post */
        Body_search_api_v1_search_post: {
            /** Canvas Height */
            canvas_height: number;
            /** Canvas Width */
            canvas_width: number;
            /** Image */
            image: string;
            /** Point Count */
            point_count: number;
            /** Revision */
            revision: number;
            selected_style?: components["schemas"]["StyleSelection"] | null;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Stroke Count */
            stroke_count: number;
            /** Strokes */
            strokes?: string | null;
            /** Text Hint */
            text_hint?: string | null;
        };
        /**
         * CropBox
         * @description Crop coordinates in source-image pixel space (inclusive-exclusive).
         */
        CropBox: {
            /** Height */
            height: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * CurationCandidate
         * @description One candidate asset for review.
         */
        CurationCandidate: {
            /** Asset Id */
            asset_id: string;
            crop?: components["schemas"]["CropBox"] | null;
            /** Height */
            height: number;
            /** Line Art Url */
            line_art_url: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "native_line_art" | "extracted_line_art";
            primary_style: components["schemas"]["PrimaryStyle"];
            /** Quality Score */
            quality_score: number;
            /**
             * Review State
             * @enum {string}
             */
            review_state: "unreviewed" | "accepted" | "rejected" | "quarantined";
            /** Scopes */
            scopes: components["schemas"]["ScopeLabel"][];
            /** Sfw Confidence */
            sfw_confidence: number;
            /** Sfw Safe */
            sfw_safe: boolean;
            /** Source Work Id */
            source_work_id: string;
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Width */
            width: number;
        };
        /**
         * CurationProgress
         * @description Overall review progress plus style/scope breakdowns.
         */
        CurationProgress: {
            /** Accepted */
            accepted: number;
            /** By Scope */
            by_scope: {
                [key: string]: components["schemas"]["ScopeBreakdown"];
            };
            /** By Style */
            by_style: {
                [key: string]: components["schemas"]["StyleBreakdown"];
            };
            /** Rejected */
            rejected: number;
            /** Remaining */
            remaining: number;
            /** Reviewed */
            reviewed: number;
            /**
             * Target
             * @default 2000
             */
            target: number;
        };
        /** EventRequest */
        EventRequest: {
            /** Asset Id */
            asset_id: string;
            event: components["schemas"]["InteractionEvent"];
            /** Query Revision */
            query_revision: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            style: components["schemas"]["PrimaryStyle"];
        };
        /** EventResponse */
        EventResponse: {
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Api Version */
            api_version: string;
            /** Cuda Available */
            cuda_available: boolean;
            /** Curation Enabled */
            curation_enabled: boolean;
            /** Dataset Version */
            dataset_version: string | null;
            /**
             * Device
             * @enum {string}
             */
            device: "cuda" | "cpu";
            /**
             * Disabled Branches
             * @description Optional retrieval branches disabled this session, e.g. pose.
             */
            disabled_branches: string[];
            /** Fixture Mode */
            fixture_mode: boolean;
            /** Gallery Size */
            gallery_size: number;
            /** Gpu Name */
            gpu_name: string | null;
            /** Index Version */
            index_version: string | null;
            /** Models */
            models: components["schemas"]["ModelVersion"][];
            /** Ready */
            ready: boolean;
            /** Schema Version */
            schema_version: number;
            /** Torch Version */
            torch_version: string | null;
            /** Vram Total Mb */
            vram_total_mb: number | null;
            /**
             * Warmup
             * @enum {string}
             */
            warmup: "pending" | "complete" | "skipped";
            /** Warnings */
            warnings: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InteractionEvent
         * @enum {string}
         */
        InteractionEvent: "open" | "pin" | "unpin" | "trace";
        /**
         * LabelRequest
         * @description Body of ``POST /curation/labels``.
         */
        LabelRequest: {
            /** Asset Id */
            asset_id: string;
            crop?: components["schemas"]["CropBox"] | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "keep" | "reject";
            /**
             * Malformed Anatomy
             * @default false
             */
            malformed_anatomy: boolean;
            /** Note */
            note?: string | null;
            /**
             * Poor Extraction
             * @default false
             */
            poor_extraction: boolean;
            primary_style?: components["schemas"]["PrimaryStyle"] | null;
            /** Quality */
            quality?: number | null;
            /** Reviewer */
            reviewer?: string | null;
            /** Scopes */
            scopes?: components["schemas"]["ScopeLabel"][] | null;
        };
        /** LabelResponse */
        LabelResponse: {
            /** Asset Id */
            asset_id: string;
            /** Created At */
            created_at: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "keep" | "reject";
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: number;
            /** Review Quality */
            review_quality: number | null;
            /**
             * Review State
             * @enum {string}
             */
            review_state: "unreviewed" | "accepted" | "rejected" | "quarantined";
        };
        /**
         * LineArtOrigin
         * @description Whether the visible reference is native line art or machine-extracted.
         * @enum {string}
         */
        LineArtOrigin: "native_line_art" | "extracted_line_art";
        /** ModelVersion */
        ModelVersion: {
            /** Device */
            device?: string | null;
            /** Loaded */
            loaded: boolean;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** PreferencesResponse */
        PreferencesResponse: {
            /** Affinities */
            affinities: components["schemas"]["StyleAffinity"][];
            /** Learning Enabled */
            learning_enabled: boolean;
            /**
             * Row Order
             * @description Style-row order after Best Match: explicit style first, then learned affinity, then the fixed default order as tie-breaker.
             */
            row_order: components["schemas"]["PrimaryStyle"][];
            selected_style: components["schemas"]["PrimaryStyle"] | null;
        };
        /**
         * PreferencesUpdate
         * @description Partial update; omitted fields are left unchanged.
         */
        PreferencesUpdate: {
            /**
             * Clear Selected Style
             * @description Clear the explicit style.
             * @default false
             */
            clear_selected_style: boolean;
            /** Learning Enabled */
            learning_enabled?: boolean | null;
            /**
             * Reset Affinities
             * @default false
             */
            reset_affinities: boolean;
            /** @description Explicitly select a style. Ignored unless provided. */
            selected_style?: components["schemas"]["PrimaryStyle"] | null;
        };
        /**
         * PrimaryStyle
         * @description Exactly one primary style per asset. Also the five reference-panel rows.
         * @enum {string}
         */
        PrimaryStyle: "manga_anime" | "western_ink" | "realistic_academic" | "cartoon" | "gesture_sketch";
        /**
         * ScopeBreakdown
         * @description Reviewed/accepted/rejected counts for a single scope bucket.
         */
        ScopeBreakdown: {
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Remaining */
            remaining: number;
            /** Reviewed */
            reviewed: number;
        };
        /**
         * ScopeLabel
         * @description What part of a character (or how many characters) an image depicts.
         *
         *     An asset may carry several scope labels; queries return one probability per
         *     label plus ``unknown``.
         * @enum {string}
         */
        ScopeLabel: "eye" | "face_head" | "hair" | "hand" | "foot" | "upper_body_clothing" | "full_body" | "multi_character" | "unknown";
        /** ScopePrediction */
        ScopePrediction: {
            /** Confidence */
            confidence: number;
            label: components["schemas"]["ScopeLabel"];
        };
        /** SearchGroup */
        SearchGroup: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "best_match" | "style" | "provisional_scope";
            /** Results */
            results: components["schemas"]["SearchResult"][];
            scope?: components["schemas"]["ScopeLabel"] | null;
            style?: components["schemas"]["PrimaryStyle"] | null;
            /** Title */
            title: string;
        };
        /**
         * SearchMode
         * @enum {string}
         */
        SearchMode: "insufficient" | "provisional" | "confident";
        /** SearchResponse */
        SearchResponse: {
            /** Groups */
            groups: components["schemas"]["SearchGroup"][];
            mode: components["schemas"]["SearchMode"];
            /**
             * Revision
             * @description Echoes the request revision unchanged.
             */
            revision: number;
            /** Scope Predictions */
            scope_predictions: components["schemas"]["ScopePrediction"][];
            timing: components["schemas"]["SearchTiming"];
            /** Warning */
            warning?: string | null;
        };
        /** SearchResult */
        SearchResult: {
            /** Asset Id */
            asset_id: string;
            /**
             * Asset Url
             * @description Trace-compatible full asset URL.
             */
            asset_url: string;
            origin: components["schemas"]["LineArtOrigin"];
            /** Quality */
            quality: number;
            /**
             * Relevance
             * @description Calibrated relevance probability.
             */
            relevance: number;
            /** Scopes */
            scopes: components["schemas"]["ScopeLabel"][];
            style: components["schemas"]["PrimaryStyle"];
            /** Thumbnail Url */
            thumbnail_url: string;
        };
        /** SearchTiming */
        SearchTiming: {
            /** Embedding Ms */
            embedding_ms: number;
            /** Preprocessing Ms */
            preprocessing_ms: number;
            /** Reranking Ms */
            reranking_ms: number;
            /** Retrieval Ms */
            retrieval_ms: number;
            /** Total Ms */
            total_ms: number;
        };
        /**
         * SnapshotResponse
         * @description Body of ``POST /curation/snapshots``.
         */
        SnapshotResponse: {
            /** Created At */
            created_at: string;
            /** Label Count */
            label_count: number;
            /** Path */
            path: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Style Breakdown */
            style_breakdown: {
                [key: string]: number;
            };
        };
        /** Stroke */
        Stroke: {
            /**
             * Pointer
             * @enum {string}
             */
            pointer: "pen" | "mouse" | "touch";
            /** Points */
            points: components["schemas"]["StrokePoint"][];
            /**
             * Tool
             * @enum {string}
             */
            tool: "pressure" | "monoline" | "eraser";
        };
        /**
         * StrokePoint
         * @description One sampled pointer position inside the gzipped ``strokes`` field.
         */
        StrokePoint: {
            /**
             * P
             * @description Normalized pressure.
             */
            p: number;
            /**
             * T
             * @description Milliseconds since the stroke sequence started.
             */
            t: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** StrokeSequence */
        StrokeSequence: {
            /** Canvas Height */
            canvas_height: number;
            /** Canvas Width */
            canvas_width: number;
            /** Strokes */
            strokes: components["schemas"]["Stroke"][];
            /**
             * Version
             * @default 1
             * @constant
             */
            version: 1;
        };
        /** StyleAffinity */
        StyleAffinity: {
            /**
             * Affinity
             * @description Laplace-smoothed, decayed share.
             */
            affinity: number;
            style: components["schemas"]["PrimaryStyle"];
        };
        /**
         * StyleBreakdown
         * @description Reviewed/accepted/rejected counts for a single style family.
         */
        StyleBreakdown: {
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Remaining */
            remaining: number;
            /** Reviewed */
            reviewed: number;
        };
        /**
         * StyleSelection
         * @description ``selected_style`` multipart value: a style enum or ``all``.
         * @enum {string}
         */
        StyleSelection: "all" | "manga_anime" | "western_ink" | "realistic_academic" | "cartoon" | "gesture_sketch";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_asset_file_api_v1_assets__asset_id___kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_label_api_v1_curation_labels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_candidate_api_v1_curation_next_get: {
        parameters: {
            query?: {
                /** @description Filter by scope bucket */
                scope?: components["schemas"]["ScopeLabel"] | null;
                /** @description Filter by primary style */
                style?: components["schemas"]["PrimaryStyle"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurationCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_api_v1_curation_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurationProgress"];
                };
            };
        };
    };
    export_snapshot_api_v1_curation_snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
        };
    };
    record_event_api_v1_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_preferences_api_v1_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
        };
    };
    update_preferences_api_v1_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_search_api_v1_search_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Malformed image or strokes */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid field */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const curationCandidateOriginValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CurationCandidate"]["origin"]> = ["native_line_art", "extracted_line_art"];
export const curationCandidateReview_stateValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CurationCandidate"]["review_state"]> = ["unreviewed", "accepted", "rejected", "quarantined"];
export const healthResponseDeviceValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["HealthResponse"]["device"]> = ["cuda", "cpu"];
export const healthResponseWarmupValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["HealthResponse"]["warmup"]> = ["pending", "complete", "skipped"];
export const interactionEventValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["InteractionEvent"]> = ["open", "pin", "unpin", "trace"];
export const labelRequestDecisionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LabelRequest"]["decision"]> = ["keep", "reject"];
export const labelResponseDecisionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LabelResponse"]["decision"]> = ["keep", "reject"];
export const labelResponseReview_stateValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LabelResponse"]["review_state"]> = ["unreviewed", "accepted", "rejected", "quarantined"];
export const lineArtOriginValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LineArtOrigin"]> = ["native_line_art", "extracted_line_art"];
export const primaryStyleValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["PrimaryStyle"]> = ["manga_anime", "western_ink", "realistic_academic", "cartoon", "gesture_sketch"];
export const scopeLabelValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ScopeLabel"]> = ["eye", "face_head", "hair", "hand", "foot", "upper_body_clothing", "full_body", "multi_character", "unknown"];
export const searchGroupKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SearchGroup"]["kind"]> = ["best_match", "style", "provisional_scope"];
export const searchModeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SearchMode"]> = ["insufficient", "provisional", "confident"];
export const strokePointerValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Stroke"]["pointer"]> = ["pen", "mouse", "touch"];
export const strokeToolValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Stroke"]["tool"]> = ["pressure", "monoline", "eraser"];
export const styleSelectionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["StyleSelection"]> = ["all", "manga_anime", "western_ink", "realistic_academic", "cartoon", "gesture_sketch"];
